import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Link from "next/link";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <Navbar />
        {children}
        <footer className="bg-gray-800 text-white p-4 text-center">
          © {new Date().getFullYear()} Bytemeuh Zoo. Tous droits réservés.
          <div>
            Site réalisé par{" "}
            <a
              href="https://www.linkedin.com/in/mijosé-difuidi-5bbbb21b2/"
              className="text-blue-500 hover:underline"
            >
              Mijosé DIFUIDI
            </a>
            <div className="flex justify-center mt-2 space-x-4">
              <Link href="https://www.linkedin.com/company/bytemeuh-zoo/">
                <Image src="/images/linkedin.svg" alt="linkedin" width={30} height={30} />
              </Link>
              <Link href="https://www.instagram.com/bytemeuh_zoo/">
                <Image src="/images/instagram.svg" alt="instagram" width={30} height={30} />
              </Link>
              <Link href="https://x.com/bytemeuhzoo/">
                <Image src="/images/twitter.svg" alt="twitter" width={30} height={30} />
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
