import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Link from "next/link";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <Navbar />
        {children}
        <footer className="bg-gray-800 text-white p-4 text-center">
            <div className="flex flex-wrap justify-center space-x-6 mb-2">
                <Link href="/" className="hover:text-blue-500">
                Accueil
                </Link>
                <Link href="/actualites" className="hover:text-blue-500">
                Actualités
                </Link>
                <Link href="/services" className="hover:text-blue-500">
                Services
                </Link>
                <Link href="/activites" className="hover:text-blue-500">
                Activités
                </Link>
            </div>
          © {new Date().getFullYear()} Bytemeuh Zoo. Tous droits réservés.
          <div>
            Site réalisé par{" "}
            <a
              href="https://www.linkedin.com/in/mijosé-difuidi-5bbbb21b2/"
              className="text-blue-500 hover:underline"
            >
              Mijosé DIFUIDI
            </a>
            <div className="flex justify-center mt-2 space-x-4">
              <a
                href="https://www.linkedin.com/company/bytemeuh-zoo/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/images/linkedin.svg"
                  alt="linkedin"
                  width={30}
                  height={30}
                />
              </a>
              <a
                href="https://www.instagram.com/bytemeuh_zoo/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/images/instagram.svg"
                  alt="instagram"
                  width={30}
                  height={30}
                />
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
